---
swagger: 3.0.0
info:
  title: IIoT Portal API Gateway
  description: ""
  contact: {}
  version: "1.0"
servers:
- url: https://virtserver.swaggerhub.com/vincenthp2603/aal-wise21-b4x-dialog/1.0
  description: SwaggerHub API Auto Mocking
paths:
  /api:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        "200":
          description: ""
  /api/assets:
    get:
      operationId: AssetsController_find
      parameters:
      - name: ProductInstanceUri
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
      - name: PublisherInstanceUri
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
      responses:
        "200":
          description: ""
    post:
      operationId: AssetsController_create
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostAssetDto'
        required: true
      responses:
        "201":
          description: ""
    delete:
      operationId: AssetsController_delete
      parameters:
      - name: ProductInstanceUri
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: ""
  /api/events:
    get:
      operationId: EventsController_find
      parameters:
      - name: ProductInstanceUri
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
      responses:
        "200":
          description: ""
    post:
      operationId: EventsController_create
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostEventDto'
        required: true
      responses:
        "201":
          description: ""
  /api/alarms:
    get:
      operationId: AlarmsController_find
      parameters:
      - name: ProductInstanceUri
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
      responses:
        "200":
          description: ""
    post:
      operationId: AlarmsController_create
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostAlarmDto'
        required: true
      responses:
        "201":
          description: ""
  /api/alarms/{id}:
    put:
      operationId: AlarmsController_update
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutAlarmDto'
        required: true
      responses:
        "200":
          description: ""
    delete:
      operationId: AlarmsController_delete
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: ""
components:
  schemas:
    Geolocation:
      required:
      - latitude
      - longitude
      type: object
      properties:
        longitude:
          type: string
          example: "12"
        latitude:
          type: string
          example: "12"
    PostAssetDto:
      required:
      - DeviceClass
      - DeviceManual
      - DeviceRevision
      - HardwareRevision
      - Manufacturer
      - ManufacturerUri
      - Model
      - ProductCode
      - ProductInstanceUri
      - PublisherInstanceUri
      - RevisionCounter
      - SerialNumber
      - SoftwareRevision
      type: object
      properties:
        Manufacturer:
          type: string
          example: Murrelektronik Gmbh
        ManufacturerUri:
          type: string
          example: murrelektronik.com
        Model:
          type: string
          example: VarioX
        ProductCode:
          type: string
          example: X-Quad 1.5
        HardwareRevision:
          type: string
          example: "1"
        SoftwareRevision:
          type: string
          example: "2"
        DeviceRevision:
          type: string
          example: V1.3.8.0
        DeviceManual:
          type: string
          example: some-url.com
        DeviceClass:
          type: string
          example: Gateway
        SerialNumber:
          type: string
          example: 09800202xxxxx
        ProductInstanceUri:
          type: string
          example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
        RevisionCounter:
          type: number
          example: 1
        PublisherInstanceUri:
          type: string
          example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
        status:
          type: string
          example: online
        remoteManagementUrl:
          type: string
          example: http://11.12.13.6
        geolocation:
          example:
            longitude: "12"
            latitude: "12"
          allOf:
          - $ref: '#/components/schemas/Geolocation'
    PostEventDto:
      required:
      - ProductInstanceUri
      - name
      type: object
      properties:
        ProductInstanceUri:
          type: string
          example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
        name:
          type: string
          example: Running
    PostAlarmDto:
      required:
      - ProductInstanceUri
      - description
      - severity
      - status
      type: object
      properties:
        severity:
          type: string
          example: warning
        description:
          type: string
          example: Lost connection to a connected device
        status:
          type: string
          example: active
        ProductInstanceUri:
          type: string
          example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
    PutAlarmDto:
      type: object
      properties:
        severity:
          type: string
          example: warning
        description:
          type: string
          example: Lost connection to a connected device
        status:
          type: string
          example: active
        ProductInstanceUri:
          type: string
          example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
