swagger: '2.0'
info:
  contact: {}
  description: ''
  title: IIoT Portal API Gateway
  version: '1.0'
paths:
  /api:
    get:
      parameters: []
      responses:
        '200':
          description: ''
      operationId: AppController_getHello
  /api/alarms:
    get:
      parameters:
        - in: query
          name: ProductInstanceUri
          required: false
          type: string
          x-example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
      responses:
        '200':
          description: ''
      operationId: AlarmsController_find
    post:
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/PostAlarmDto'
      responses:
        '201':
          description: ''
      operationId: AlarmsController_create
  '/api/alarms/{id}':
    delete:
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: ''
      operationId: AlarmsController_delete
    put:
      consumes:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/PutAlarmDto'
      responses:
        '200':
          description: ''
      operationId: AlarmsController_update
  /api/assets:
    delete:
      parameters:
        - in: query
          name: ProductInstanceUri
          required: true
          type: string
      responses:
        '200':
          description: ''
      operationId: AssetsController_delete
    get:
      parameters:
        - in: query
          name: ProductInstanceUri
          required: false
          type: string
          x-example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
        - in: query
          name: PublisherInstanceUri
          required: false
          type: string
          x-example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
      responses:
        '200':
          description: ''
      operationId: AssetsController_find
    post:
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/PostAssetDto'
      responses:
        '201':
          description: ''
      operationId: AssetsController_create
  /api/events:
    get:
      parameters:
        - in: query
          name: ProductInstanceUri
          required: false
          type: string
          x-example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
      responses:
        '200':
          description: ''
      operationId: EventsController_find
    post:
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/PostEventDto'
      responses:
        '201':
          description: ''
      operationId: EventsController_create
definitions:
  Geolocation:
    properties:
      latitude:
        example: '12'
        type: string
      longitude:
        example: '12'
        type: string
    required:
      - longitude
      - latitude
    type: object
  PostAlarmDto:
    properties:
      ProductInstanceUri:
        example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
        type: string
      description:
        example: Lost connection to a connected device
        type: string
      severity:
        example: warning
        type: string
      status:
        example: active
        type: string
    required:
      - severity
      - description
      - status
      - ProductInstanceUri
    type: object
  PostAssetDto:
    properties:
      DeviceClass:
        example: Gateway
        type: string
      DeviceManual:
        example: some-url.com
        type: string
      DeviceRevision:
        example: V1.3.8.0
        type: string
      HardwareRevision:
        example: '1'
        type: string
      Manufacturer:
        example: Murrelektronik Gmbh
        type: string
      ManufacturerUri:
        example: murrelektronik.com
        type: string
      Model:
        example: VarioX
        type: string
      ProductCode:
        example: X-Quad 1.5
        type: string
      ProductInstanceUri:
        example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
        type: string
      PublisherInstanceUri:
        example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
        type: string
      RevisionCounter:
        example: 1
        type: number
      SerialNumber:
        example: 09800202xxxxx
        type: string
      SoftwareRevision:
        example: '2'
        type: string
      geolocation:
        allOf:
          - $ref: '#/definitions/Geolocation'
        example:
          latitude: '12'
          longitude: '12'
      remoteManagementUrl:
        example: 'http://11.12.13.6'
        type: string
      status:
        example: online
        type: string
    required:
      - Manufacturer
      - ManufacturerUri
      - Model
      - ProductCode
      - HardwareRevision
      - SoftwareRevision
      - DeviceRevision
      - DeviceManual
      - DeviceClass
      - SerialNumber
      - ProductInstanceUri
      - RevisionCounter
      - PublisherInstanceUri
    type: object
  PostEventDto:
    properties:
      ProductInstanceUri:
        example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
        type: string
      name:
        example: Running
        type: string
    required:
      - ProductInstanceUri
      - name
    type: object
  PutAlarmDto:
    properties:
      ProductInstanceUri:
        example: murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx
        type: string
      description:
        example: Lost connection to a connected device
        type: string
      severity:
        example: warning
        type: string
      status:
        example: active
        type: string
    type: object
tags: []
x-components: {}

