# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Geolocation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, latitude: str=None, longitude: str=None):  # noqa: E501
        """Geolocation - a model defined in Swagger

        :param latitude: The latitude of this Geolocation.  # noqa: E501
        :type latitude: str
        :param longitude: The longitude of this Geolocation.  # noqa: E501
        :type longitude: str
        """
        self.swagger_types = {
            'latitude': str,
            'longitude': str
        }

        self.attribute_map = {
            'latitude': 'latitude',
            'longitude': 'longitude'
        }

        self._latitude = latitude
        self._longitude = longitude

    @classmethod
    def from_dict(cls, dikt) -> 'Geolocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Geolocation of this Geolocation.  # noqa: E501
        :rtype: Geolocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def latitude(self) -> str:
        """Gets the latitude of this Geolocation.


        :return: The latitude of this Geolocation.
        :rtype: str
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude: str):
        """Sets the latitude of this Geolocation.


        :param latitude: The latitude of this Geolocation.
        :type latitude: str
        """
        if latitude is None:
            raise ValueError("Invalid value for `latitude`, must not be `None`")  # noqa: E501

        self._latitude = latitude

    @property
    def longitude(self) -> str:
        """Gets the longitude of this Geolocation.


        :return: The longitude of this Geolocation.
        :rtype: str
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: str):
        """Sets the longitude of this Geolocation.


        :param longitude: The longitude of this Geolocation.
        :type longitude: str
        """
        if longitude is None:
            raise ValueError("Invalid value for `longitude`, must not be `None`")  # noqa: E501

        self._longitude = longitude
