---
swagger: "3.0.0"
info:
  description: ""
  version: "1.0"
  title: "IIoT Portal API Gateway"
  contact: {}
paths:
  /api:
    get:
      operationId: "app_controller_get_hello"
      parameters: []
      responses:
        "200":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /api/assets:
    get:
      operationId: "assets_controller_find"
      parameters:
      - name: "ProductInstanceUri"
        in: "query"
        required: false
      - name: "PublisherInstanceUri"
        in: "query"
        required: false
      responses:
        "200":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    post:
      operationId: "assets_controller_create"
      parameters: []
      responses:
        "201":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    delete:
      operationId: "assets_controller_delete"
      parameters:
      - name: "ProductInstanceUri"
        in: "query"
        required: true
      responses:
        "200":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /api/events:
    get:
      operationId: "events_controller_find"
      parameters:
      - name: "ProductInstanceUri"
        in: "query"
        required: false
      responses:
        "200":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    post:
      operationId: "events_controller_create"
      parameters: []
      responses:
        "201":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /api/alarms:
    get:
      operationId: "alarms_controller_find"
      parameters:
      - name: "ProductInstanceUri"
        in: "query"
        required: false
      responses:
        "200":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    post:
      operationId: "alarms_controller_create"
      parameters: []
      responses:
        "201":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /api/alarms/{id}:
    put:
      operationId: "alarms_controller_update"
      parameters:
      - name: "id"
        in: "path"
        required: true
      responses:
        "200":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    delete:
      operationId: "alarms_controller_delete"
      parameters:
      - name: "id"
        in: "path"
        required: true
      responses:
        "200":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions: {}
