---
swagger: "2.0"
info:
  description: ""
  version: "1.0"
  title: "IIoT Portal API Gateway"
  contact: {}
tags: []
paths:
  /api:
    get:
      operationId: "app_controller_get_hello"
      parameters: []
      responses:
        "200":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /api/alarms:
    get:
      operationId: "alarms_controller_find"
      parameters:
      - name: "ProductInstanceUri"
        in: "query"
        required: false
        type: "string"
        x-example: "murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx"
      responses:
        "200":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    post:
      operationId: "alarms_controller_create"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/PostAlarmDto"
      responses:
        "201":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /api/alarms/{id}:
    put:
      operationId: "alarms_controller_update"
      consumes:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/PutAlarmDto"
      responses:
        "200":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    delete:
      operationId: "alarms_controller_delete"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /api/assets:
    get:
      operationId: "assets_controller_find"
      parameters:
      - name: "ProductInstanceUri"
        in: "query"
        required: false
        type: "string"
        x-example: "murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx"
      - name: "PublisherInstanceUri"
        in: "query"
        required: false
        type: "string"
        x-example: "murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx"
      responses:
        "200":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    post:
      operationId: "assets_controller_create"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/PostAssetDto"
      responses:
        "201":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    delete:
      operationId: "assets_controller_delete"
      parameters:
      - name: "ProductInstanceUri"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /api/events:
    get:
      operationId: "events_controller_find"
      parameters:
      - name: "ProductInstanceUri"
        in: "query"
        required: false
        type: "string"
        x-example: "murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx"
      responses:
        "200":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    post:
      operationId: "events_controller_create"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/PostEventDto"
      responses:
        "201":
          description: ""
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Geolocation:
    type: "object"
    required:
    - "latitude"
    - "longitude"
    properties:
      latitude:
        type: "string"
        example: "12"
      longitude:
        type: "string"
        example: "12"
  PostAlarmDto:
    type: "object"
    required:
    - "ProductInstanceUri"
    - "description"
    - "severity"
    - "status"
    properties:
      ProductInstanceUri:
        type: "string"
        example: "murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx"
      description:
        type: "string"
        example: "Lost connection to a connected device"
      severity:
        type: "string"
        example: "warning"
      status:
        type: "string"
        example: "active"
    example:
      severity: "warning"
      description: "Lost connection to a connected device"
      ProductInstanceUri: "murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx"
      status: "active"
  PostAssetDto:
    type: "object"
    required:
    - "DeviceClass"
    - "DeviceManual"
    - "DeviceRevision"
    - "HardwareRevision"
    - "Manufacturer"
    - "ManufacturerUri"
    - "Model"
    - "ProductCode"
    - "ProductInstanceUri"
    - "PublisherInstanceUri"
    - "RevisionCounter"
    - "SerialNumber"
    - "SoftwareRevision"
    properties:
      DeviceClass:
        type: "string"
        example: "Gateway"
      DeviceManual:
        type: "string"
        example: "some-url.com"
      DeviceRevision:
        type: "string"
        example: "V1.3.8.0"
      HardwareRevision:
        type: "string"
        example: "1"
      Manufacturer:
        type: "string"
        example: "Murrelektronik Gmbh"
      ManufacturerUri:
        type: "string"
        example: "murrelektronik.com"
      Model:
        type: "string"
        example: "VarioX"
      ProductCode:
        type: "string"
        example: "X-Quad 1.5"
      ProductInstanceUri:
        type: "string"
        example: "murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx"
      PublisherInstanceUri:
        type: "string"
        example: "murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx"
      RevisionCounter:
        type: "number"
        example: 1.0
      SerialNumber:
        type: "string"
        example: "09800202xxxxx"
      SoftwareRevision:
        type: "string"
        example: "2"
      geolocation:
        $ref: "#/definitions/PostAssetDto_geolocation"
      remoteManagementUrl:
        type: "string"
        example: "http://11.12.13.6"
      status:
        type: "string"
        example: "online"
    example:
      RevisionCounter: 1.0
      PublisherInstanceUri: "murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx"
      remoteManagementUrl: "http://11.12.13.6"
      ManufacturerUri: "murrelektronik.com"
      ProductCode: "X-Quad 1.5"
      DeviceClass: "Gateway"
      SoftwareRevision: "2"
      DeviceRevision: "V1.3.8.0"
      DeviceManual: "some-url.com"
      SerialNumber: "09800202xxxxx"
      Manufacturer: "Murrelektronik Gmbh"
      Model: "VarioX"
      HardwareRevision: "1"
      ProductInstanceUri: "murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx"
      geolocation: "{\"latitude\":\"12\",\"longitude\":\"12\"}"
      status: "online"
  PostEventDto:
    type: "object"
    required:
    - "ProductInstanceUri"
    - "name"
    properties:
      ProductInstanceUri:
        type: "string"
        example: "murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx"
      name:
        type: "string"
        example: "Running"
    example:
      name: "Running"
      ProductInstanceUri: "murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx"
  PutAlarmDto:
    type: "object"
    properties:
      ProductInstanceUri:
        type: "string"
        example: "murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx"
      description:
        type: "string"
        example: "Lost connection to a connected device"
      severity:
        type: "string"
        example: "warning"
      status:
        type: "string"
        example: "active"
    example:
      severity: "warning"
      description: "Lost connection to a connected device"
      ProductInstanceUri: "murrelektronik.com/VarioX/X-Quad%201.5/09800202xxxxx"
      status: "active"
  PostAssetDto_geolocation:
    type: "object"
    example: "{\"latitude\":\"12\",\"longitude\":\"12\"}"
x-components: {}
