name: generate-template
run-name: Generate development template
on:
  push:
    branches:
      - template
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.PAT }}
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Setup build tools
        run: |
         git clone https://github.com/swagger-api/swagger-codegen
         npm i api-spec-converter
         npm i -g openapi-to-postmanv2
      - name: Build server stub
        run: |
         api-spec-converter -f openapi_3 -t swagger_2 -s yaml api-spec.json > swagger-spec.yaml
         mkdir -p server
         cd swagger-codegen
         mvn clean package
         java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
              -i ../swagger-spec.yaml \
              -l python-flask \
              -o ../generated-server
         cd ..
         rm -r swagger-codegen
         rm swagger-spec.yaml
      - name: Generate Postman collection
        run: |
         openapi2postmanv2 -s api-spec.yaml -o postman-collection.json
      - name: Push generated codes to a new branch
        run: |
         git config --global user.name "${{ github.actor }}"
         git_hash=$(git rev-parse --short "$GITHUB_SHA")        
         new_branch="template-$git_hash"
         commit_msg="${{ github.event.head_commit.message }}"
         commit_time="$(date)"
         git switch -c $new_branch
         git add .         
         git commit -m "$git_hash - $commit_time: $commit_msg"
         git push --set-upstream origin $new_branch
