name: github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: |
         ls
         git clone https://github.com/swagger-api/swagger-codegen
         cd swagger-codegen
         mvn clean package
         cd ..
         java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
              -i swagger-spec.json \
              -l python-flask \
              -o generated-server
         ls
              
