name: github-actions
run-name: Generate server-stub
on:
  push:
    branches:
      - server-stub-build
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          #token: ${{ secrets.PAT }}
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build server stub
        run: |
         git clone https://github.com/swagger-api/swagger-codegen
         cd swagger-codegen
         mvn clean package > /dev/null
         java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
              -i ../swagger-spec.json \
              -l python-flask \
              -o ../generated-server
         cd ..
         rm -r swagger-codegen
         git config --global user.name "${{ github.actor }}"
         git add .
         git commit -m "Server stub generated"
      - name: Push generated server stub to a new branch
        run: |
         git_hash=$(git rev-parse --short "$GITHUB_SHA")        
         new_branch="server-stub-$git_hash"
         git branch $new_branch         
         git commit -m "$git_hash - $(date): ${{ github.event.head_commit.message }}"
         git push --set-upstream origin $new_branch
         
#git commit -m "Server-stub generated"
#git_hash=$(git rev-parse --short "$GITHUB_SHA")        
#new_branch="server-stub-$git_hash"
#git branch $new_branch
#git add .
#git commit -m "$git_hash - $(date): ${{ github.event.head_commit.message }}"
#git push --set-upstream origin $new_branch
