name: github-actions
run-name: Generate development template
on:
  push:
    branches:
      - template
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          #token: ${{ secrets.PAT }}
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Setup build tools
        run: |
         git clone https://github.com/swagger-api/swagger-codegen
         npm i -g openapi-to-postmanv2
      - name: Build server stub
        run: |
         mkdir -p generated-server
         cd swagger-codegen
         mvn clean package
         java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
              -i ../api-spec.yaml \
              -l python-flask \
              -o ../generated-server
         cd ..
         rm -r swagger-codegen
      - name: Generate Postman collection
        run: |
         cp api-spec.yaml swagger-spec.yaml
         sed 's/openapi: 3.0.0/swagger: 3.0.0/g'
         openapi2postmanv2 -s swagger-spec.yaml -o postman-collection.json
         rm swagger-spec.yaml
      - name: Push generated codes to a new branch
        run: |
         git config --global user.name "${{ github.actor }}"
         git_hash=$(git rev-parse --short "$GITHUB_SHA")        
         new_branch="template-$git_hash"
         git switch -c $new_branch
         git add .         
         git commit -m "$git_hash - $(date): ${{ github.event.head_commit.message }}"
         git push --set-upstream origin $new_branch      
