name: github-actions
run-name: Generate server-stub
on:
  push:
    branches:
      - server-stub-build
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: |
         git clone https://github.com/swagger-api/swagger-codegen
         cd swagger-codegen
         mvn clean package > /dev/null
         java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
              -i ../swagger-spec.json \
              -l python-flask \
              -o ../generated-server
         cd ..
         rm -r swagger-codegen
      - run: |
         echo "$(git rev-parse --short "$GITHUB_SHA")"        
#git branch server-stub-$(git rev-parse --short "$GITHUB_SHA") 
         
         
                    
