name: template-pull-request
run-name: Create pull request for the generated codes
on:
  push:
    branches:
      - 'template-*'
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: peter-evans/create-pull-request@v4
        with:
          base: dev
          branch: ${{ github.ref_name }}
          commit-message: ${{ github.event.head_commit.message }}
