name: template-pull-request
run-name: Create pull request for the generated codes
on:
  push:
    branches:
      - 'template-*'
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - uses: peter-evans/create-pull-request@v4
        with:
          base: dev
          branch: dev
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          commit-message: "Pull request: ${{ github.event.head_commit.message }}"
